### ISSUE TITLE
feature map visualization?

### ISSUE THREAD

**Issue by RayYellow** [CalayZhou/MBNet#27]
同学你好，首先非常感谢你杰出的工作。
我对特征图可视化的过程很感兴趣，也尝试使用matplotlib实现了一下，但是没有成功。
请问可以提供特征图可视化的代码参考一下吗，谢谢。

**Comment by RayYellow** [comment]
已解决

**Comment by cqyan521** [comment]
> 已解决

你好,请问您是如何解决的,可以分享一下吗?
