### ISSUE TITLE
Kaist数据集问题

### ISSUE THREAD

**Issue by dongdongyee** [CalayZhou/MBNet#29]
作者您好！感谢您分享这么优秀的工作！

请教您关于KAIST数据集的一个细节：关于数据集里的label好像不止有person，还有people, cyclist,person?，这些标签您在training阶段和testing阶段是如何处理的呢？是统一都归类成person么？

提前感谢您的回复！

**Comment by CalayZhou** [comment]
您好，感谢对我们工作的关注~数据集里的label例如person，people, cyclist,person等全部包含在训练集中，统一归类为person，测试集则依照论文提到的中Liu et al改进后的标签，以统一测试标准

**Comment by dongdongyee** [comment]
作者您好！感谢您之前的回复，还有一个问题想向您请教。您在做testing的时候，是否清洗或者后处理过Liu et al改进后的标签？
我在改训练模型的时候发现，模型在validation set上表现很好，MR可以降到0.10以下，AP50也有0.97左右，但testing set上MR很差，大约0.45，AP50只有0.73，想请教您是不是testing set的标签需要再清洗或者处理一下，感谢您的指导！

**Comment by dongdongyee** [comment]
就比如说，您下载了Liu et al改进后的标签后，是否过滤过尺寸特小的人（e.g. <40 pixel)? 是否有其他类似这样的处理呢？感谢您的指导！

**Comment by dongdongyee** [comment]
作者您好，请问
