### ISSUE TITLE
关于MBNet/data/result的结果

### ISSUE THREAD

**Issue by dongdongyee** [CalayZhou/MBNet#30]
作者您好，再次感谢您分享优秀的工作，冒昧再次打扰：

请问，您当前repo中MBNet/data/result/路径下的结果，是您的论文中展示的KAIST数据集上的最优结果么？

感谢您的回复与指导！

**Comment by CalayZhou** [comment]
您好，因为训练结果有一定波动性，MBNet/data/result/路径下的结果我记得比论文中结果会好一些，可以说是模型在KAIST数据集上的最优结果~

**Comment by dongdongyee** [comment]
感谢解答！
