### ISSUE TITLE
数据处理的问题

### ISSUE THREAD

**Issue by WestHan33** [CalayZhou/MBNet#32]
尊敬的作者您好，非常感谢您的代码，我自己制作了多光谱的数据集，想用您的代码训练跑一下，请问如何能将自己的训练数据转为npy格式呢？能否提供一下您的数据转换的代码，谢谢您。

**Comment by CalayZhou** [comment]
您好，可以参考CVC14数据集读取的代码，只要按照npy标签文件的的格式对应修改就可

**Comment by WestHan33** [comment]
好的，谢谢您。
