### ISSUE TITLE
No module named 'keras_MBNet.utils.bbox'

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [CalayZhou/MBNet#4]
Hi, 
     I am trying to run "demo.py" but I got this error.  
Please see the attached image for details. 

I am using the following system and libraries. 
Ubuntu: 16.04
Cuda: 10.0
CuDNN: 7.4.1
Python: 3.6.10
TensorFlow: 1.15.0

 I have searched errors in the ALFNet project but it does not have this kind of error. I also tried to import bbox.pyx file using some other ways but still got some errors.  

![bbox2](https://user-images.githubusercontent.com/28862708/91001355-0f567680-e5fe-11ea-92ea-5546574e4ac3.png)

**Comment by MuhammadAsadJaved** [comment]
I saw you mentioned in the project that if Cuda and CuDNN are different then compile "nms" and "utils" according to the given link. I will try it and then let you know if still there is any problem.

**Comment by CalayZhou** [comment]
> I saw you mentioned in the project that if Cuda and CuDNN are different then compile "nms" and "utils" according to the given link. I will try it and then let you know if still there is any problem.

sorry, i find the file `bbox.so ` was not uploaded by git yesterday, i will update it right now.

**Comment by MuhammadAsadJaved** [comment]
@CalayZhou  OK. Thank you.

**Comment by MuhammadAsadJaved** [comment]
@CalayZhou  bbox problem resolved and now there is another error. 

Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    from keras_MBNet.model.MBNetModel import MBNetModel
  File "/media/asad/0A9AD66165F33762/MBNet/keras_MBNet/model/MBNetModel.py", line 8, in <module>
    from keras_MBNet import bbox_process
  File "/media/asad/0A9AD66165F33762/MBNet/keras_MBNet/bbox_process.py", line 10, in <module>
    from .nms_wrapper import nms
  File "/media/asad/0A9AD66165F33762/MBNet/keras_MBNet/nms_wrapper.py", line 12, in <module>
    from .nms.gpu_nms import gpu_nms
ModuleNotFoundError: No module named 'keras_MBNet.nms.gpu_nms'

Does it also require .so file? if so then please upload. 
These nms files are different from https://github.com/endernewton/tf-faster-rcnn  or it's the same? 
Can we run in the cpu mode to avoid this error for just a demo?

**Comment by CalayZhou** [comment]
yes,the gpu_nms.so has just been uploaded, you can find it at ./keras_MBNet/nms/gpu_nms.so. The nms files are compiled according to the https://github.com/endernewton/tf-faster-rcnn but they are not same. The cpu mode is not supported and i will try it.

**Comment by MuhammadAsadJaved** [comment]
The updated code with  .so files can run without any modifications and errors. 

Thank you for your cooperation. 
Stay blessed.
