### ISSUE TITLE
problems about data preprocess in CVC14_txt_to_numpy.txt

### ISSUE THREAD

**Issue by SunnyWuYang** [CalayZhou/MBNet#41]
Thanks for your team providing such wonderful work!
I have some questions about the code in CVC14_txt_to_numpy.txt. 
I noticed that in read_x1_x2_y1_y2_from_txt_annotations() function, the x2, y2 are resized to 470(original value is 512), however, in bbox_info_combine_aligned() function, they are resized again( multiple 1.087). 
1. What's the purpose of doing this? 
2. Do both the Kaist dataset and the CVC-14 dataset use this operation?

**Comment by CalayZhou** [comment]
Thanks for your attention! This is because the original size of images in CVC-14 is 640\*471, the original  size of images in Kaist  is 640\*512. To apply the same implementation, we resize 640\*471 (CVC-14) to 640*512 (KAIST) .

**Comment by SunnyWuYang** [comment]
Thanks for your reply!
