### ISSUE TITLE
KAIST子集问题

### ISSUE THREAD

**Issue by Sharkpeppers** [CalayZhou/MBNet#62]
您好，很抱歉再次打扰您。请问您是怎样在KAIST的九个子集进行测试的？或者说我如何将这些注释分为9个类别，包括：Rea. | Day | Night | Near | Medium | Far | None | Partial | Heavy。

**Comment by qiherong** [comment]
同问，请问下您会划分了吗

**Comment by Sharkpeppers** [comment]
会了😃
