### ISSUE TITLE
关于代码中光照感知模块的问题

### ISSUE THREAD

**Issue by dearsyx** [CalayZhou/MBNet#64]
您好，非常感谢您提出的工作和开源的代码，在运行代码的过程中我遇到了一些问题
如何在保证网络能够正常运行的情况下删除掉光照感知模块，或者将融合时使用到的光照权重设置为固定值

**Comment by CalayZhou** [comment]
您好，只要把Illumination_Gate相关的代码注释掉就可以了

**Comment by dearsyx** [comment]
好的，非常感谢您的回复
