### ISSUE TITLE
Testing on the CVC-14 dataset 

### ISSUE THREAD

**Issue by akanuasiegbu** [CalayZhou/MBNet#70]
Hi, for the CVC-14 dataset, I am trying to evaluate the testing images, there appear to be some images in the visible spectrum that don't have corresponding images in the thermal spectrum and vice versa (images in the thermal spectrum that are not in the RGB spectrum). I have two questions. 1) Are the images with non-corresponding images just ignored in the evaluation? 2) Since the multimodal images are not aligned which modality is being used for evaluation?

![image](https://github.com/CalayZhou/MBNet/assets/51218092/eed2ea93-d8ed-4197-ad2a-d4de31c137d8)
![image](https://github.com/CalayZhou/MBNet/assets/51218092/de31b47b-3c33-4c6e-be54-705448a5210a)

**Comment by akanuasiegbu** [comment]
Looking at https://github.com/CalayZhou/MBNet/files/5352777/CVC14_txt_to_numpy.txt it appears that we would only use the images that appear in both the thermal and visible modality and that only the the visible modality annotations are used for testing. Is that correct?

**Comment by CalayZhou** [comment]
hello, only the the visible modality annotations  are adopted as GTs for testing, and  images that appear in both the thermal and visible modality are used in CVC14.

**Comment by akanuasiegbu** [comment]
Also one more question for the CVC-14 dataset related to testing. There does not appear to be an occlusion label when looking at data: `x, y, w1, h1, one, zero1, zero2, zero3, zero4, num, zero5`. So I am assuming that for missrate during evaluation we do not need to account for occlusion?

**Comment by CalayZhou** [comment]
hello, the occlusion can be ignored  during CVC-14 evaluation.
