### ISSUE TITLE
Do you have a pytorch version implementation of this project?

### ISSUE THREAD

**Issue by ningding-o** [CalayZhou/MBNet#9]
Do you have a pytorch version implementation of this project?

**Comment by CalayZhou** [comment]
Sorry, due to the limited time,  we have not implemented the code with pytorch. You can have  a try~

**Comment by ningding-o** [comment]
> Sorry, due to the limited time, we have not implemented the code with pytorch. You can have a try~

Thx for reply, I'll try to reimplement it using pytorch if time permits.   Anyway your work is very helpful.

**Comment by yh19970806** [comment]
> > Sorry, due to the limited time, we have not implemented the code with pytorch. You can have a try~
> 
> Thx for reply, I'll try to reimplement it using pytorch if time permits. Anyway your work is very helpful.



> > Sorry, due to the limited time, we have not implemented the code with pytorch. You can have a try~
> 
> Thx for reply, I'll try to reimplement it using pytorch if time permits. Anyway your work is very helpful.

I am implementing it using pytorch ,but met some problems unsolved. Are you still working for it?

**Comment by aminkashiri** [comment]
> > > Sorry, due to the limited time, we have not implemented the code with pytorch. You can have a try~
> > 
> > 
> > Thx for reply, I'll try to reimplement it using pytorch if time permits. Anyway your work is very helpful.
> 
> > > Sorry, due to the limited time, we have not implemented the code with pytorch. You can have a try~
> > 
> > 
> > Thx for reply, I'll try to reimplement it using pytorch if time permits. Anyway your work is very helpful.
> 
> I am implementing it using pytorch ,but met some problems unsolved. Are you still working for it?

Could you finish your implementation? Maybe we could think on your unsolved problem together
